### ISSUE TITLE
Working dir changes unintuitively

### ISSUE THREAD

**Issue by Mandera** [arsenetar/send2trash#40]
Minimum code for re-creating behaviour:
```
from send2trash import send2trash
import os
import pathlib

# Get current working dir
workingDir = os.getcwd()

# Suffix "\folder"
folderDir = "{}\\folder".format(workingDir)

# Create that new folder
pathlib.Path(folderDir).mkdir(parents=True, exist_ok=True)

# Set working dir to new folder
os.chdir(folderDir)

# Print new working dir
print(os.getcwd())

# Send that folder to trash
send2trash(folderDir)

# Current working dir has unintuitively been changed
print(os.getcwd())
```

- Windows 7 64-bit
- Python 3.8
- PyCharm 2020.1

Took some time to find this bug in my code, I don't know if it's intentional or not, but it seems weird that the working dir has to be changed. In my case I use send2trash to trash a folder and then re-create the folder to clear it.

A popular equivalent to delete a folder is this below, and that doesn't change the working dir. It does however throw a PermissionError when trying to delete a parent folder to current working dir if ignore_errors is False.

```
import shutil
shutil.rmtree(folderDir, ignore_errors=True)
```

**Comment by arsenetar** [comment]
I think the behavior you are seeing most likely has to do with how windows handles this. For example if you have an explorer window open inside a folder which is sent to the recycle bin / deleted it will back up to the closest existing parent directory. (This matches the behavior you described.)  Since we are calling a windows interface, I don't believe there is a way to change this.

Additionally when I run `shutil.rmtree(folderDir, ignore_errors=True)` and I am inside the folder it does not actually delete the folder, it just does not throw the error.  It will remove the contents of the folder though.  

If you want to send the contents of the folder to trash in your use case I would suggest passing the contents of the folder to send2trash. If sending the whole folder to trash is desired (then creating it again) is desired then I would keep pythons `cwd` in a directory above the folder when performing the operation.

**Comment by arsenetar** [comment]
Closing this as this appears to be a windows behavior and nothing we can do about it.
